-- retrieve_data.cql

USE mykeyspace;

-- Retrieve data from Products Table
SELECT * FROM Products;

-- Retrieve data from Warehouses Table
SELECT * FROM Warehouses;

-- Retrieve data from Suppliers Table
SELECT * FROM Suppliers;

-- Retrieve data from Orders Table
SELECT * FROM Orders;

-- Retrieve data from OrderDetails Table
SELECT * FROM OrderDetails;

-- Retrieve data from Shipments Table
SELECT * FROM Shipments;

-- Retrieve data from InventoryLevels Table
SELECT * FROM InventoryLevels;
